FROM oven/bun:alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY . /app

RUN bun install

RUN bun ./scripts/build.ts

FROM oven/bun:alpine

WORKDIR /app

COPY --from=builder /app/build /app

CMD ["bun", "./index.js"]