FROM oven/bun:alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY . /app

RUN bun install

RUN bun build --target=bun --outfile=build/index.js src/index.ts
RUN bun build --target=bun --outfile=build/set-webhook.js scripts/set-webhook.ts

FROM oven/bun:alpine

WORKDIR /app

COPY --from=builder /app/build /app

CMD bun run ./set-webhook.js && bun run ./index.js