name: Build and Publish Image

on:
  workflow_dispatch:

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t m_little_bot -f Dockerfile.prod .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag m_little_bot registry.digitalocean.com/ascrazy/m_little_bot:latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/ascrazy/m_little_bot:latest
