name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  is_master_push: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test

  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun biome:ci

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun prettier:check

  build:
    runs-on: ubuntu-latest
    needs: [test, biome, prettier]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: i.alexandr.sh@gmail.com
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            registry.digitalocean.com/ascrazy/m_little_bot
          tags: |
            type=raw,value=latest,enable=${{ env.is_master_push }}
            type=ref,event=branch
            type=ref,event=pr
      - uses: docker/build-push-action@v6
        with:
          context: packages/mlb-backend
          file: packages/mlb-backend/Dockerfile.prod
          push: ${{ env.is_master_push }}
          tags: ${{ steps.meta.outputs.tags }}
